import { test, expect } from "@playwright/test";

// Stale/absent booth QR token hard-blocks order entry (feat/booth-qr-token).
// REQUIRES the coffee-cart seed (supabase/seed/coffee-cart.sql) — this is the
// "Kopitiam Cart" booth id, same as customer-order.spec.ts.
const BOOTH = "c0ffee01-0000-4000-8000-000000000001";

// access_token is a per-environment CSPRNG value generated by the
// `gen_booth_token()` Postgres default (supabase/migrations/0025_booth_access_token.sql)
// and rotated by `regenerate_booth_token` — the seed never pins it to a fixed
// string, and no e2e spec here uses a DB client to read one out (the existing
// specs only ever drive the app through the browser). So the happy path (a
// valid `?k=` renders the menu) isn't assertable from this spec without
// hacking in a DB client the other specs don't use; it belongs in
// customer-order.spec.ts once that spec's navigation is wired to carry a real
// token (e.g. resolved the same way the vendor QR page gets it). This spec
// covers only the two token-less/wrong-token hard-block cases, which need
// nothing beyond the booth existing.
test.describe("stale QR token", () => {
  test("bare link (no token) hard-blocks", async ({ page }) => {
    await page.goto(`/order/${BOOTH}`);
    await expect(page.getByText(/this code expired/i)).toBeVisible();
  });

  test("wrong token hard-blocks", async ({ page }) => {
    await page.goto(`/order/${BOOTH}?k=definitely-wrong`);
    await expect(page.getByText(/this code expired/i)).toBeVisible();
  });
});
